services:
  - type: web
    name: sounkoue
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: "Soun KouÃª"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:Nl9Wn4qCmGk0T5exai8oX6CT+mhTf+wNSrAOAF+STek=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://sounkoue.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d4mun11r0fns73ah6e1g-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: sounkoue_db
      - key: DB_USERNAME
        value: sounkoue_user
      - key: DB_PASSWORD
        value: o1oaDCavj9OqpITOPvJtsObq1NXbgZXo
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error