services:
  - type: web
    name: sounkoue
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: sounkoue
          property: host
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d4mun11r0fns73ah6e1g-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: sounkoue_db
      - key: DB_USERNAME
        value: sounkoue_user
      - key: DB_PASSWORD
        value: o1oaDCavj9OqpITOPvJtsObq1NXbgZXo
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync